### ISSUE TITLE
Accept only number 

### ISSUE THREAD

**Issue by cedric-the-king** [DJWOMS/vue-tel-input#1]
Hi I've been using vue-tel-input since a while and I have found it very useful. Good Job. However I'm wondering how to make it  only display digit characters. I've tried to use regex but it doesn't work as I want.

**Comment by Ethan0007** [comment]
Hello, 

I have same question , how can i accept only number?
Thanks

**Comment by cedric-the-king** [comment]
I've found a trick to solve the problem using ref on the component:  ref='vueTelInput'

And in the mounted lifecycle hook

  mounted: function () {
    this.$refs.vueTelInput.$refs.input.addEventListener('keydown', e => {
      if (isNaN(e.key) && e.keyCode !== 8) {
        e.preventDefault()
      }
    })
  }
